# Numpy:

In [ ]:
numerical python

In [ ]:
why Numpy?

Memory efficient container that provides fast numerical operations.


In [15]:
#python list
l=range(1000)
%timeit [i**2 for i in l]

722 µs ± 78.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
import numpy as np
a=np.arange(1000)
%timeit a**2

3.76 µs ± 385 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
#Example for calculate BMI using List. Is it possible?
h=[1.71,1.58,1.51,1.76,1.38]
w=[68.5,45.6,78.6,45.8,56.9]
BMI=w/h **2
print(BMI)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [13]:
#Example for calculating of BMI using numpy array. Is it possible?
h=[1.71,1.58,1.51,1.76,1.38]
w=[68.5,45.6,78.6,45.8,56.9]
import numpy as np
nh=np.array(h)
nw=np.array(w)
BMI=nw/nh **2
print(BMI)



[23.42601142 18.26630348 34.47217227 14.7856405  29.87817685]


# Creation of arrays using numpy:

In [ ]:
Manual creation of arrays

In [3]:
#1D array creation
import numpy as np
a=np.array([0,1,2,3,4])
print(a)
a
type(a)

[0 1 2 3 4]


numpy.ndarray

In [4]:
#to know dimensions of array
a.ndim

1

In [5]:
#To know shape of array
a.shape

(5,)

In [6]:
#2D,3D,4D.....
b=np.array([[0,1,2,3],[4,5,6,7]])
print(b)

[[0 1 2 3]
 [4 5 6 7]]


In [7]:
#to know dimensions
b.ndim

2

In [8]:
#to know shape
b.shape

(2, 4)

In [9]:
#3D
c=np.array([[[1,2,3],[4,5,6]],[[7,6,5],[5,4,3]],[[2,3,4],[4,5,6]]])
print(c)

[[[1 2 3]
  [4 5 6]]

 [[7 6 5]
  [5 4 3]]

 [[2 3 4]
  [4 5 6]]]


In [10]:
c.ndim

3

In [16]:
c.shape

(3, 2, 3)

In [17]:
print(len(c))

3


# len()

In [ ]:
It prints the first dimension of array (rows)

In [15]:
x=np.array([[1,2,3,4],[5,6,7,8]])
print(len(x))
print(x.ndim)
x.shape

2
2


(2, 4)

## Functions to create arrays

### arange():

In [1]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
b=np.arange(5,20,2)
print(b)

[ 5  7  9 11 13 15 17 19]


In [3]:
b=np.arange(2,20,2)
print(b)

[ 2  4  6  8 10 12 14 16 18]


### linear space

In [4]:
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [5]:
a=np.linspace(10,16,6)
print(a)

[10.  11.2 12.4 13.6 14.8 16. ]


In [6]:
#to create zeros array
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#to create ones array
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
#Eye matrix creation 
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### diagonal function

In [9]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [10]:
#to extract diagonal elements
np.diag(a)

array([1, 2, 3, 4])

In [11]:
#to create array with random elements
a=np.random.rand(4)
print(a)

[0.80697968 0.79783326 0.63320427 0.85879832]


In [12]:
a=np.random.randn(4)
print(a)

[ 0.87256298 -0.11219219  0.37421745 -1.87202619]


In [15]:
a=np.random.randint(2,18,8)
print(a)

[ 4 16  2  5  9  2  2  9]


# Basic Datatypes:

In [16]:
a=np.arange(10)
a.dtype

dtype('int32')

In [19]:
a=np.arange(10,dtype='float64')
print(a.dtype)
print(a)

float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [20]:
a=np.arange(10,dtype='int64')
print(a.dtype)
print(a)

int64
[0 1 2 3 4 5 6 7 8 9]


In [21]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
a=np.zeros((3,3),dtype='int64')
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [23]:
#complex array
d=np.array([1+2j,2+4j])
print(d.dtype)

complex128


In [24]:
#boolian array
b=np.array([True,False,True,True])
print(b.dtype)

bool


In [25]:
s=np.array(["Hello","Suresh","Laxmi","Venky"])
print(s.dtype)

<U6


## Indexing & Slicing:

## Indexing

In [26]:
a=np.arange(10)
print(a[5])

5


In [27]:
a=np.diag([1,2,3,4])
print(a[2,2])

3


In [28]:
a=np.diag([1,2,3,4])
print(a[2,3])

0


In [29]:
#assigning values to multidimensional array
a[2,3]=10
print(a)

[[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  3 10]
 [ 0  0  0  4]]


## Slicing

In [30]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
#slicing
print(a[1:8])

[1 2 3 4 5 6 7]


In [32]:
#slicing
print(a[1:8:2])

[1 3 5 7]


In [33]:
#slicing
print(a[::2])

[0 2 4 6 8]


In [34]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [36]:
a[1:2]=100
print(a)

[  0 100   2   3   4   5   6   7   8   9]


In [37]:
a[5:]=100
print(a)

[  0 100   2   3   4 100 100 100 100 100]


In [38]:
b=np.arange(10)
print(b)
b[4:8]=28
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 28 28 28 28  8  9]


In [44]:
a=np.arange(10)
print(a)
c=np.arange(5)
a[5:]=c[::-1]
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 4 3 2 1 0]


# Copies and Views:

A slicing operation creates a view on the original array, which is a way of accessing array data.

The original array is not copied in memory. You can use np.may_share_memory() or np.shares_memory() to check if two arrays shares the same memory block.

In [2]:
#example 
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
b=a[::2]
print(b)

[0 2 4 6 8]


In [4]:
print(id(a))
print(id(b))

1731534479968
1731656153888


In [5]:
np.shares_memory(a,b)

True

In [10]:
b[0]=100
print(b)
print(a)

[100   2   4   6   8]
[100   1   2   3   4   5   6   7   8   9]


In [8]:
#example with lists slicing
l=[1,2,3,4,5,6]
l2=l[::2]
print(l2)
np.shares_memory(l,l2)

[1, 3, 5]


False

In [9]:
l2[0]=100
print(l2)
print(l)

[100, 3, 5]
[1, 2, 3, 4, 5, 6]


In [11]:
#example copy of array
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
c=a[::2].copy() #forced copy
print(c)
np.shares_memory(a,c)

[0 2 4 6 8]


False

In [13]:
c[0]=200
print(c)
print(a)

[200   2   4   6   8]
[0 1 2 3 4 5 6 7 8 9]


## Fancy Indexing:

In [ ]:
Numpy array can be indexed with slicing but also boolian or integer indexing.

This method is called fancy indexing.

### Using boolian mask

In [14]:
a=np.random.randint(0,20,15)
print(a)

[10 16  5 15 18  0  0  6  3  0  7 16 14 12  0]


In [15]:
mask=(a%2==0)

x=a[mask]
print(x)

[10 16 18  0  0  6  0 16 14 12  0]


In [16]:
a[mask]=99

In [17]:
print(a)

[99 99  5 15 99 99 99 99  3 99  7 99 99 99 99]


In [25]:
b=np.arange(20)
print(b)
mask=(b%2!=0)
y=b[mask]
print(y)
print(type(y))
print(type(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [28]:
y=-1
print(y)
print(type(y))
#b[0]=200
print(type(b))

-1
<class 'int'>
<class 'int'>


In [20]:
b[mask]=-1

print(b)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


## Numerical Operations

In [29]:
import numpy as np



### 1. Elementwise operations:

Basic Operations:

In [30]:
a=np.array([1,2,3,4,5])
print(a)
a+1

[1 2 3 4 5]


array([2, 3, 4, 5, 6])

In [31]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [34]:
b=np.ones(5)+1
print(b)

[2. 2. 2. 2. 2.]


In [36]:
print(a)
print(b)
a-b

[1 2 3 4 5]
[2. 2. 2. 2. 2.]


array([-1.,  0.,  1.,  2.,  3.])

In [37]:
a*b

array([ 2.,  4.,  6.,  8., 10.])

In [38]:
#matrix multiplication
c=np.diag([1,2,3,4])
print(c)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [39]:
print(c*c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [40]:
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [41]:
x=np.diag([1,2,3])
y=np.diag([4,5,6,7])
print(x*y)

ValueError: operands could not be broadcast together with shapes (3,3) (4,4) 

# Comparisions:

In [42]:
#elementwise comparisions
a=np.array([1,2,3,4])
b=np.array([5,4,3,4])
a==b

array([False, False,  True,  True])

In [43]:
#arraywise comparisions
a=np.array([1,2,3,4])
b=np.array([5,4,3,4])
c=np.array([1,2,3,4])
np.array_equal(a,b)


False

In [44]:
np.array_equal(a,c)

True

# Logical Operations

In [1]:
import numpy as np
a=np.array([1,1,0,0], dtype='bool')
b=np.array([1,0,1,0], dtype='bool')
np.logical_or(a,b)

array([ True,  True,  True, False])

In [2]:
import numpy as np
a=np.array([1,1,0,0], dtype='bool')
b=np.array([1,0,1,0], dtype='bool')
np.logical_and(a,b)

array([ True, False, False, False])

In [3]:
import numpy as np
a=np.array([1,1,0,0], dtype='bool')
b=np.array([1,0,1,0], dtype='bool')
np.logical_not(a)

array([False, False,  True,  True])

# Transcendental functions:

In [5]:
a=np.arange(5)
print(a)
np.sin(a)

[0 1 2 3 4]


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [6]:
np.log(a)

C:\Users\venky\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [7]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# shape mismatch:

In [8]:
a=np.arange(4)
a+np.array([2,4])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Basic Reductions:

### computing sums:

In [9]:
x=np.array([1,2,3,4,5,6,7])
np.sum(x)

28

In [10]:
#sum by rows and by columnwise
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [11]:
x.sum(axis=0) #columnwise sum


array([5, 7, 9])

In [12]:
x.sum(axis=1) #rowwise sum

array([ 6, 15])

In [13]:
#minimum 
x=np.array([3,2,10])
x.min()

2

In [14]:
x.max()

10

In [15]:
#index 
x.argmax()

2

In [16]:
x.argmin()

1

# logical operations:

In [17]:
np.all([True,False,True,True])

False

In [18]:
np.all([True,True,True,True])

True

In [19]:
np.any([True,False,True,False])

True

In [20]:
np.any([True,False,False,False])

True

In [21]:
np.any([False,False,False,False])

False

In [22]:
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])
((a<=b)&(b<=c)).all()

True

# Statistics

In [23]:
x=np.array([1,2,3,1])
y=np.array([[1,2,3],[4,5,6]])
x.mean()

1.75

In [27]:
np.mean(y,axis=1)

array([2., 5.])

In [24]:
np.median(x)

1.5

In [26]:
np.median(y,axis=1)

array([2., 5.])

In [28]:
x.std() #standard deviation

0.82915619758885

# Broadcasting:

Basic operations on numpy arrays (addition, multiplication) are elementwise 
This works on arrays of the same size. If u try to apply on different size arrays it will give value error. To overcome this drawback we have broadcasting concept in numpy by transforming sizes.

In [29]:
a=np.tile(np.arange(0,40,10),(3,1))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [30]:
a=a.T
print(a)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [31]:
b=np.array([0,1,2])
print(b)

[0 1 2]


In [32]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [35]:
a=np.arange(0,40,10)
print(a.shape)
print(a)

(4,)
[ 0 10 20 30]


In [36]:
a=a[:,np.newaxis]
a.shape

(4, 1)

In [37]:
print(a)

[[ 0]
 [10]
 [20]
 [30]]


In [38]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])