In [1]:
import numpy as np

In [2]:
#python lists
l=range(1000)
%timeit [i**2 for i in l]


929 µs ± 80.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
#with numpy
a=np.arange(1000)
%timeit a**2

4.32 µs ± 415 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# 1. Creating Arrays

In [15]:
#1-D Array
a=np.array([[0,1,2,5,8]])
print(a)
print(type(a))

[[0 1 2 5 8]]
<class 'numpy.ndarray'>


In [7]:
l=[10,20,30]
print(l)
type(l)

[10, 20, 30]


list

In [8]:
a.ndim

1

In [9]:
a.shape

(5,)

In [10]:
#2D array
b=np.array([[1,2,3],[3,4,5]])
print(b)

[[1 2 3]
 [3 4 5]]


In [11]:
b.shape

(2, 3)

In [12]:
b.ndim

2

In [16]:
len(a)

1

In [14]:
len(b)

2

In [20]:
#3D array
c=np.array([[[0,1,4],[2,3,6]],[[4,5,8],[6,7,9]]])
print(c)

[[[0 1 4]
  [2 3 6]]

 [[4 5 8]
  [6 7 9]]]


In [21]:
c.ndim

3

In [22]:
c.shape

(2, 2, 3)

# Functions for array creation

In [24]:

a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
b=np.arange(1,23,3)
print(b)

[ 1  4  7 10 13 16 19 22]


# linear spacing

In [27]:
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [29]:
a=np.linspace(0,10,10)
print(a)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [30]:
#common arrays
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
b=np.zeros((3,3))

In [32]:
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
#eye
c=np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
#diagonal function
a=np.diag([2,2,2,2])
print(a)

[[2 0 0 0]
 [0 2 0 0]
 [0 0 2 0]
 [0 0 0 2]]


In [36]:
np.diag(a)

array([2, 2, 2, 2])

In [37]:
a=np.random.rand(4)
print(a)

[0.01232873 0.79964441 0.48830237 0.25167095]


In [38]:
a=np.random.randn(4)
print(a)

[ 0.5578381  -0.59626585 -0.02434533  1.09960648]


# Data Types 

In [39]:
a=np.arange(10)
a.dtype


dtype('int32')

In [40]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [43]:
a=np.arange(10,dtype='float64')
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [2]:
#complex data type
import numpy as np
d=np.array([1+2j,3+5j])
d.dtype6

dtype('complex128')

In [3]:
print(d)

[1.+2.j 3.+5.j]


In [4]:
#boolian data type
b=np.array([True,False,False,True])
print(b.dtype)
print(b)

bool
[ True False False  True]


In [6]:
#string
s=np.array(["Venky","Sudhir","Manohar","Suresh","Hello"])
s.dtype

dtype('<U7')

In [7]:
print(s)

['Venky' 'Sudhir' 'Manohar' 'Suresh' 'Hello']


# Indexing and slicing

In [8]:
s=np.array(["Venky","Sudhir","Manohar","Suresh","Hello"])
print(s[0])

Venky


In [9]:
print(s[-1])

Hello


In [10]:
x=np.diag([2,3,4])
print(x)

[[2 0 0]
 [0 3 0]
 [0 0 4]]


In [12]:
print(x[1][1])

3


In [13]:
x[0,1]=6
print(x)

[[2 6 0]
 [0 3 0]
 [0 0 4]]


# slicing

In [14]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
print(a[2:5])

[2 3 4]


In [17]:
print(a[2:9:2])

[2 4 6 8]


In [18]:
print(a[:])

[0 1 2 3 4 5 6 7 8 9]


In [19]:
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [20]:
print(id(a))

2015703268608


In [21]:
y=np.arange(10)
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
z=y[:10:2]
print(z)

[0 2 4 6 8]


In [24]:
np.may_share_memory(y,b)

False

In [29]:
print(id(y))

2015703294240


In [30]:
print(id(z))

2015703201712


In [31]:
z[0]=100
print(y)

[100   1   2   3   4   5   6   7   8   9]


In [37]:
p=np.arange(20)
print(p)
q=p[2:12:2].copy()
print(q)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  4  6  8 10]


In [38]:
np.may_share_memory(p,q)

False

In [33]:
print(id(p))
print(id(q))

2015703300976
2015703301776


In [34]:
q[0]=233
print(p)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [39]:
p=np.arange(20)
print(p)
q=p
print(q)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [40]:
np.may_share_memory(p,q)

True

In [36]:
q[0]=999
print(p)

[999   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


# Boolean Masking

In [58]:
a=np.random.randint(0,20,15)
print(a)

[ 5  9  3  9  1 14 13  8 11 18  9  0 17  8  3]


In [59]:
mask=(a%3==0)

In [60]:
x=a[mask]

In [61]:
print(x)

[ 9  3  9 18  9  0  3]


In [63]:
a[mask]=999
print(a)

[  5 999 999 999   1  14  13   8  11 999 999 999  17   8 999]


# Numerical Operations on Numpy

In [1]:
import numpy as np

# Elementwise Operations

In [ ]:
1. Basic Operations


In [4]:
a=np.array([1,2,3,4])
print(a)
a=a+1
print(a)

[1 2 3 4]
[2 3 4 5]


In [5]:
a**2

array([ 4,  9, 16, 25], dtype=int32)

In [10]:
b=np.ones(4)+4

In [11]:
print(b)

[5. 5. 5. 5.]


In [12]:
a+b

array([ 7.,  8.,  9., 10.])

In [13]:
a-b

array([-3., -2., -1.,  0.])

In [15]:
a*b

array([10., 15., 20., 25.])

In [16]:
c=np.diag([1,2,3,4])
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [17]:
print(c*c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [18]:
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


# Comparisions 

In [19]:
a=np.array([1,2,3,4])
b=np.array([2,3,3,4])
a==b

array([False, False,  True,  True])

# Arraywise comparisions

In [20]:
a=np.array([1,2,3,4])
b=np.array([2,3,3,4])
c=np.array([1,2,3,4])
np.array_equal(a,b)

False

In [21]:
np.array_equal(a,c)

True

# logical Operations

In [24]:
a=np.array([1,1,0,0],dtype=bool)
b=np.array([1,0,1,0], dtype=bool)
np.logical_or(a,b)

array([False, False,  True,  True])

In [27]:
a=np.array([1,1,0,0],dtype=bool)
b=np.array([1,0,1,0], dtype=bool)
np.logical_and(a,b)

array([ True, False, False, False])

In [28]:
a=np.array([1,1,0,0],dtype=bool)
b=np.array([1,0,1,0], dtype=bool)
np.logical_not(a)

array([False, False,  True,  True])

In [26]:
a=np.array([10,13,0,0])
b=np.array([1,0,1,0], dtype=bool)
np.logical_not(a)

array([False, False,  True,  True])

# Transendental functions

In [29]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [30]:
np.log(a)

C:\Users\venky\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [31]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [32]:
a=np.arange(4)
print(a)

[0 1 2 3]


In [33]:
a+np.array([2,3])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Basic Reductions

In [ ]:
computing sums

In [35]:
a=np.array([1,2,3,4])
np.sum(a)

10

In [36]:
#sum by rowS and by columns
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [37]:
x.sum(axis=0)

array([4, 6])

In [38]:
x.sum(axis=1)

array([3, 7])

In [39]:
x=np.array([2,12,23,1])
x.min()

1

In [40]:
x.max()

23

In [45]:
a=np.zeros((50,50))
print(a)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [46]:
np.any(a!=0)

False

In [47]:
b=np.ones(4)

In [49]:
np.any(b!=0)

True

In [52]:
c=np.zeros((20,20))
np.all(c==c)

True

In [53]:
np.all(a==c)

C:\Users\venky\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

# Statistics

In [54]:
x=np.array([1,2,3,4])
y=np.array([[1,2,3],[4,5,6]])
x.mean()

2.5

In [57]:
y.mean(axis=1)

array([2., 5.])

In [58]:
np.median(x)

2.5

In [59]:
x.std()

1.118033988749895